version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:80"  # Mapeia a porta 9090 do host para a porta 80 do contêiner (onde o NGINX serve a aplicação)
    restart: always
